[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "coordinator"
path = "src/main.rs"

[lib]
name = "coordinator"
path = "src/lib.rs"

[dependencies]
shared = { path = "../shared" }
blind-rsa-signatures = { workspace = true }
sha2 = { workspace = true }
zeroize = { workspace = true }
hmac = { workspace = true }
bitcoin = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "1"
rand = "0.8"
